name: Lobby
version: '${project.version}'
main: net.spigotcloud.lobby.Lobby
api-version: 1.19
softdepend: [ PointsAPI ]
authors: [ TerryGHG ]
description: Modular Lobby Plugin for Spigot 1.19+
website: https://github.com/teraprath
