name: Lobby
version: '${project.version}'
main: dev.teraprath.lobby.Lobby
api-version: 1.19
softdepend: [ PointsAPI ]
authors: [ TerryGHG ]
description: Modular Lobby for Spigot 1.19+
website: https://github.com/teraprath
